//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Luaan.Yggmire.OrleansInterfaces.Actors
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ZoneObserverFactory
    {
        

            public static Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ZoneObserverReference.Cast(grainRef);
            }

        private static global::Orleans.CodeGeneration.IGrainMethodInvoker methodInvoker;

        public async static System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver> CreateObjectReference(Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver obj)
        {
            if (methodInvoker == null) methodInvoker = new ZoneObserverMethodInvoker();
            return ZoneObserverFactory.Cast(await global::Orleans.Runtime.GrainReference.CreateObjectReference(obj, methodInvoker));
        }

        public static System.Threading.Tasks.Task DeleteObjectReference(Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver reference)
        {
            return global::Orleans.Runtime.GrainReference.DeleteObjectReference(reference);
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansInterfaces.Actors.Luaan.Yggmire.OrleansInterfaces.Actors.IZo" +
            "neObserver")]
        internal class ZoneObserverReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver
        {
            

            public static Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver), (global::Orleans.Runtime.GrainReference gr) => { return new ZoneObserverReference(gr);}, grainRef, 1865857157);
            }
            
            protected internal ZoneObserverReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ZoneObserverReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1865857157;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansInterfaces.Actors.Luaan.Yggmire.OrleansInterfaces.Actors.IZo" +
                        "neObserver";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ZoneObserverReference input = ((ZoneObserverReference)(original));
                return ((ZoneObserverReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ZoneObserverReference input = ((ZoneObserverReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ZoneObserverReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ZoneObserverMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            void Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver.AddItems(System.Guid zoneId, Luaan.Yggmire.Core.Structures.WorldItem[] items)
            {

                base.InvokeOneWayMethod(1653213901, new object[] {zoneId, items} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansInterfaces.Actors.Luaan.Yggmire.OrleansInterfaces.Actors.IZo" +
        "neObserver", 1865857157)]
    internal class ZoneObserverMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1865857157;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1865857157:  // IZoneObserver
                        switch (methodId)
                        {
                            case 1653213901: 
                                ((IZoneObserver)grain).AddItems((System.Guid)arguments[0], (Luaan.Yggmire.Core.Structures.WorldItem[])arguments[1]); return System.Threading.Tasks.Task.FromResult((object)true);
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1865857157:  // IZoneObserver
                    switch (methodId)
                    {
                        case 1653213901:
                            return "AddItems";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansInterfaces.Chat
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ChatObserverFactory
    {
        

            public static Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ChatObserverReference.Cast(grainRef);
            }

        private static global::Orleans.CodeGeneration.IGrainMethodInvoker methodInvoker;

        public async static System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver> CreateObjectReference(Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver obj)
        {
            if (methodInvoker == null) methodInvoker = new ChatObserverMethodInvoker();
            return ChatObserverFactory.Cast(await global::Orleans.Runtime.GrainReference.CreateObjectReference(obj, methodInvoker));
        }

        public static System.Threading.Tasks.Task DeleteObjectReference(Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver reference)
        {
            return global::Orleans.Runtime.GrainReference.DeleteObjectReference(reference);
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansInterfaces.Chat.Luaan.Yggmire.OrleansInterfaces.Chat.IChatOb" +
            "server")]
        internal class ChatObserverReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver
        {
            

            public static Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver), (global::Orleans.Runtime.GrainReference gr) => { return new ChatObserverReference(gr);}, grainRef, 1633131735);
            }
            
            protected internal ChatObserverReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ChatObserverReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1633131735;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansInterfaces.Chat.Luaan.Yggmire.OrleansInterfaces.Chat.IChatOb" +
                        "server";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ChatObserverReference input = ((ChatObserverReference)(original));
                return ((ChatObserverReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ChatObserverReference input = ((ChatObserverReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ChatObserverReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ChatObserverMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            void Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver.UpdateChat(string name, string message)
            {

                base.InvokeOneWayMethod(167103139, new object[] {name, message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansInterfaces.Chat.Luaan.Yggmire.OrleansInterfaces.Chat.IChatOb" +
        "server", 1633131735)]
    internal class ChatObserverMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1633131735;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1633131735:  // IChatObserver
                        switch (methodId)
                        {
                            case 167103139: 
                                ((IChatObserver)grain).UpdateChat((System.String)arguments[0], (System.String)arguments[1]); return System.Threading.Tasks.Task.FromResult((object)true);
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1633131735:  // IChatObserver
                    switch (methodId)
                    {
                        case 167103139:
                            return "UpdateChat";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class SessionGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionGrain), -705986448, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionGrain), -705986448, primaryKey, grainClassNamePrefix));
                        }

                        public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionGrain), -705986448, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionGrain), -705986448, primaryKey, grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return SessionGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionGrain")]
        internal class SessionGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansInterfaces.ISessionGrain
        {
            

            public static Luaan.Yggmire.OrleansInterfaces.ISessionGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansInterfaces.ISessionGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionGrain), (global::Orleans.Runtime.GrainReference gr) => { return new SessionGrainReference(gr);}, grainRef, -705986448);
            }
            
            protected internal SessionGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal SessionGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -705986448;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                SessionGrainReference input = ((SessionGrainReference)(original));
                return ((SessionGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                SessionGrainReference input = ((SessionGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return SessionGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return SessionGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<string> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.GetCharacterName()
            {

                return base.InvokeMethodAsync<System.String>(1638469474, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.Authorize(string name, string password)
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation>(1891548347, new object[] {name, password} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.GetAccount()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation>(1960002325, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.CreateAccount(string name, string password)
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation>(2013465976, new object[] {name, password} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.CreateCharacter()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation>(757304272, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation> Luaan.Yggmire.OrleansInterfaces.ISessionGrain.SelectCharacter(string name)
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation>(-404060281, new object[] {name} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.RegisterObserver(Luaan.Yggmire.OrleansInterfaces.ISessionObserver observer, Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver zoneObserver)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(zoneObserver);

                return base.InvokeMethodAsync<object>(891264617, new object[] {observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.SessionObserverFactory.Cast(observer.AsReference()) : observer, zoneObserver is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Actors.ZoneObserverFactory.Cast(zoneObserver.AsReference()) : zoneObserver} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.Respond(int responseId, string response)
            {

                return base.InvokeMethodAsync<object>(-1099888414, new object[] {responseId, response} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.Disconnect()
            {

                return base.InvokeMethodAsync<object>(-1836674149, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.SubscribeForChat(int channel, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-950310688, new object[] {channel, observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.UnsubscribeFromChat(int channel, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-1965559293, new object[] {channel, observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansInterfaces.ISessionGrain.SendChatMessage(int channel, string message)
            {

                return base.InvokeMethodAsync<object>(-46125154, new object[] {channel, message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionGrain", -705986448)]
    internal class SessionGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -705986448;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -705986448:  // ISessionGrain
                        switch (methodId)
                        {
                            case 1638469474: 
                                return ((ISessionGrain)grain).GetCharacterName().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1891548347: 
                                return ((ISessionGrain)grain).Authorize((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1960002325: 
                                return ((ISessionGrain)grain).GetAccount().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 2013465976: 
                                return ((ISessionGrain)grain).CreateAccount((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 757304272: 
                                return ((ISessionGrain)grain).CreateCharacter().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -404060281: 
                                return ((ISessionGrain)grain).SelectCharacter((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 891264617: 
                                return ((ISessionGrain)grain).RegisterObserver((ISessionObserver)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1099888414: 
                                return ((ISessionGrain)grain).Respond((Int32)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1836674149: 
                                return ((ISessionGrain)grain).Disconnect().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -950310688: 
                                return ((ISessionGrain)grain).SubscribeForChat((Int32)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1965559293: 
                                return ((ISessionGrain)grain).UnsubscribeFromChat((Int32)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -46125154: 
                                return ((ISessionGrain)grain).SendChatMessage((Int32)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -705986448:  // ISessionGrain
                    switch (methodId)
                    {
                        case 1638469474:
                            return "GetCharacterName";
                    case 1891548347:
                            return "Authorize";
                    case 1960002325:
                            return "GetAccount";
                    case 2013465976:
                            return "CreateAccount";
                    case 757304272:
                            return "CreateCharacter";
                    case -404060281:
                            return "SelectCharacter";
                    case 891264617:
                            return "RegisterObserver";
                    case -1099888414:
                            return "Respond";
                    case -1836674149:
                            return "Disconnect";
                    case -950310688:
                            return "SubscribeForChat";
                    case -1965559293:
                            return "UnsubscribeFromChat";
                    case -46125154:
                            return "SendChatMessage";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class SessionObserverFactory
    {
        

            public static Luaan.Yggmire.OrleansInterfaces.ISessionObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return SessionObserverReference.Cast(grainRef);
            }

        private static global::Orleans.CodeGeneration.IGrainMethodInvoker methodInvoker;

        public async static System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.ISessionObserver> CreateObjectReference(Luaan.Yggmire.OrleansInterfaces.ISessionObserver obj)
        {
            if (methodInvoker == null) methodInvoker = new SessionObserverMethodInvoker();
            return SessionObserverFactory.Cast(await global::Orleans.Runtime.GrainReference.CreateObjectReference(obj, methodInvoker));
        }

        public static System.Threading.Tasks.Task DeleteObjectReference(Luaan.Yggmire.OrleansInterfaces.ISessionObserver reference)
        {
            return global::Orleans.Runtime.GrainReference.DeleteObjectReference(reference);
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionObserver")]
        internal class SessionObserverReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansInterfaces.ISessionObserver
        {
            

            public static Luaan.Yggmire.OrleansInterfaces.ISessionObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansInterfaces.ISessionObserver) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansInterfaces.ISessionObserver), (global::Orleans.Runtime.GrainReference gr) => { return new SessionObserverReference(gr);}, grainRef, 1563631474);
            }
            
            protected internal SessionObserverReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal SessionObserverReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1563631474;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionObserver";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                SessionObserverReference input = ((SessionObserverReference)(original));
                return ((SessionObserverReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                SessionObserverReference input = ((SessionObserverReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return SessionObserverReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return SessionObserverMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            void Luaan.Yggmire.OrleansInterfaces.ISessionObserver.ReadyForChat()
            {

                base.InvokeOneWayMethod(1287266638, new object[] {} );
            }
            
            void Luaan.Yggmire.OrleansInterfaces.ISessionObserver.Disconnected()
            {

                base.InvokeOneWayMethod(-15699575, new object[] {} );
            }
            
            void Luaan.Yggmire.OrleansInterfaces.ISessionObserver.SystemMessage(string message)
            {

                base.InvokeOneWayMethod(-1808133108, new object[] {message} );
            }
            
            void Luaan.Yggmire.OrleansInterfaces.ISessionObserver.ShowDialog(string message)
            {

                base.InvokeOneWayMethod(-377703801, new object[] {message} );
            }
            
            void Luaan.Yggmire.OrleansInterfaces.ISessionObserver.ShowInputDialog(int responseId, string message)
            {

                base.InvokeOneWayMethod(-1619562930, new object[] {responseId, message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansInterfaces.Luaan.Yggmire.OrleansInterfaces.ISessionObserver", 1563631474)]
    internal class SessionObserverMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1563631474;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1563631474:  // ISessionObserver
                        switch (methodId)
                        {
                            case 1287266638: 
                                ((ISessionObserver)grain).ReadyForChat(); return System.Threading.Tasks.Task.FromResult((object)true);
                            case -15699575: 
                                ((ISessionObserver)grain).Disconnected(); return System.Threading.Tasks.Task.FromResult((object)true);
                            case -1808133108: 
                                ((ISessionObserver)grain).SystemMessage((String)arguments[0]); return System.Threading.Tasks.Task.FromResult((object)true);
                            case -377703801: 
                                ((ISessionObserver)grain).ShowDialog((String)arguments[0]); return System.Threading.Tasks.Task.FromResult((object)true);
                            case -1619562930: 
                                ((ISessionObserver)grain).ShowInputDialog((Int32)arguments[0], (String)arguments[1]); return System.Threading.Tasks.Task.FromResult((object)true);
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1563631474:  // ISessionObserver
                    switch (methodId)
                    {
                        case 1287266638:
                            return "ReadyForChat";
                    case -15699575:
                            return "Disconnected";
                    case -1808133108:
                            return "SystemMessage";
                    case -377703801:
                            return "ShowDialog";
                    case -1619562930:
                            return "ShowInputDialog";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansInterfacesSerializers
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    using Luaan.Yggmire.Core.Structures;
    using System.Collections;
    using System.Runtime.InteropServices;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization
    {
        
        static Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(original));
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Characters = ((List<CharacterInformation>)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Characters)));
            result.Name = input.Name;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Characters, stream, typeof(List<CharacterInformation>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            result.Characters = ((List<CharacterInformation>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<CharacterInformation>), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansInterfaces_Account_CharacterInformationSerialization
    {
        
        static Luaan_Yggmire_OrleansInterfaces_Account_CharacterInformationSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation();
            result.Id = ((Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Guid), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_Core_Structures_WorldItemSerialization
    {
        
        static Luaan_Yggmire_Core_Structures_WorldItemSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            Luaan.Yggmire.Core.Structures.WorldItem input = ((Luaan.Yggmire.Core.Structures.WorldItem)(original));
            Luaan.Yggmire.Core.Structures.WorldItem result = new Luaan.Yggmire.Core.Structures.WorldItem();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Id = input.Id;
            result.PrototypeId = input.PrototypeId;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.Core.Structures.WorldItem input = ((Luaan.Yggmire.Core.Structures.WorldItem)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Int32));
            Orleans.Serialization.SerializationManager.SerializeInner(input.PrototypeId, stream, typeof(Int32));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.Core.Structures.WorldItem result = new Luaan.Yggmire.Core.Structures.WorldItem();
            result.Id = ((Int32)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int32), stream)));
            result.PrototypeId = ((Int32)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int32), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.Core.Structures.WorldItem), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
