//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Luaan.Yggmire.OrleansServerInterfaces.Account
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class AccountGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain GetGrain(long primaryKey, string keyExt)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain), 1033839444, primaryKey, keyExt));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain GetGrain(long primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain), 1033839444, primaryKey, keyExt, grainClassNamePrefix));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain GetGrain(System.Guid primaryKey, string keyExt)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain), 1033839444, primaryKey, keyExt));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain GetGrain(System.Guid primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain), 1033839444, primaryKey, keyExt,grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return AccountGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
            "es.Account.IAccountGrain")]
        internal class AccountGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain
        {
            

            public static Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain), (global::Orleans.Runtime.GrainReference gr) => { return new AccountGrainReference(gr);}, grainRef, 1033839444);
            }
            
            protected internal AccountGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal AccountGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1033839444;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
                        "es.Account.IAccountGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                AccountGrainReference input = ((AccountGrainReference)(original));
                return ((AccountGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                AccountGrainReference input = ((AccountGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return AccountGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return AccountGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<string> Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.GetName()
            {

                return base.InvokeMethodAsync<System.String>(-1256896228, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.CaptureSession(Luaan.Yggmire.OrleansInterfaces.ISessionGrain session)
            {

                return base.InvokeMethodAsync<object>(1590561359, new object[] {session is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.SessionGrainFactory.Cast(session.AsReference()) : session} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation> Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.GetState()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation>(-454132849, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.Create(string password)
            {

                return base.InvokeMethodAsync<object>(-1446207851, new object[] {password} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain> Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.CreateCharacter()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain>(757304272, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain> Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.SelectCharacter(string name)
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain>(-404060281, new object[] {name} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.CompleteCharacter(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain grain, Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation info)
            {

                return base.InvokeMethodAsync<object>(-2047775951, new object[] {grain is global::Orleans.Grain ? Luaan.Yggmire.OrleansServerInterfaces.Account.CharacterGrainFactory.Cast(grain.AsReference()) : grain, info} );
            }
            
            System.Threading.Tasks.Task<bool> Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain.ValidatePassword(string password)
            {

                return base.InvokeMethodAsync<System.Boolean>(1379941908, new object[] {password} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
        "es.Account.IAccountGrain", 1033839444)]
    internal class AccountGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1033839444;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1033839444:  // IAccountGrain
                        switch (methodId)
                        {
                            case -1256896228: 
                                return ((IAccountGrain)grain).GetName().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1590561359: 
                                return ((IAccountGrain)grain).CaptureSession((Luaan.Yggmire.OrleansInterfaces.ISessionGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -454132849: 
                                return ((IAccountGrain)grain).GetState().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1446207851: 
                                return ((IAccountGrain)grain).Create((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 757304272: 
                                return ((IAccountGrain)grain).CreateCharacter().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -404060281: 
                                return ((IAccountGrain)grain).SelectCharacter((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -2047775951: 
                                return ((IAccountGrain)grain).CompleteCharacter((ICharacterGrain)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1379941908: 
                                return ((IAccountGrain)grain).ValidatePassword((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1033839444:  // IAccountGrain
                    switch (methodId)
                    {
                        case -1256896228:
                            return "GetName";
                    case 1590561359:
                            return "CaptureSession";
                    case -454132849:
                            return "GetState";
                    case -1446207851:
                            return "Create";
                    case 757304272:
                            return "CreateCharacter";
                    case -404060281:
                            return "SelectCharacter";
                    case -2047775951:
                            return "CompleteCharacter";
                    case 1379941908:
                            return "ValidatePassword";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class CharacterGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain), 526290941, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain), 526290941, primaryKey, grainClassNamePrefix));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain), 526290941, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain), 526290941, primaryKey, grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return CharacterGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
            "es.Account.ICharacterGrain")]
        internal class CharacterGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain
        {
            

            public static Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain), (global::Orleans.Runtime.GrainReference gr) => { return new CharacterGrainReference(gr);}, grainRef, 526290941);
            }
            
            protected internal CharacterGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal CharacterGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 526290941;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
                        "es.Account.ICharacterGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                CharacterGrainReference input = ((CharacterGrainReference)(original));
                return ((CharacterGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                CharacterGrainReference input = ((CharacterGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return CharacterGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return CharacterGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<bool> Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.IsComplete()
            {

                return base.InvokeMethodAsync<System.Boolean>(-934468723, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.BindAccount(Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain account)
            {

                return base.InvokeMethodAsync<object>(1168592711, new object[] {account is global::Orleans.Grain ? Luaan.Yggmire.OrleansServerInterfaces.Account.AccountGrainFactory.Cast(account.AsReference()) : account} );
            }
            
            System.Threading.Tasks.Task<string> Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.GetName()
            {

                return base.InvokeMethodAsync<System.String>(-1256896228, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.SetName(string name)
            {

                return base.InvokeMethodAsync<object>(316304768, new object[] {name} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.Complete()
            {

                return base.InvokeMethodAsync<object>(1162765578, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation> Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.GetInfo()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation>(-1168913303, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> Luaan.Yggmire.OrleansServerInterfaces.Account.ICharacterGrain.GetZoneId()
            {

                return base.InvokeMethodAsync<System.String>(-486809198, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.Luaan.Yggmire.OrleansServerInterfac" +
        "es.Account.ICharacterGrain", 526290941)]
    internal class CharacterGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 526290941;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 526290941:  // ICharacterGrain
                        switch (methodId)
                        {
                            case -934468723: 
                                return ((ICharacterGrain)grain).IsComplete().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1168592711: 
                                return ((ICharacterGrain)grain).BindAccount((IAccountGrain)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1256896228: 
                                return ((ICharacterGrain)grain).GetName().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 316304768: 
                                return ((ICharacterGrain)grain).SetName((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1162765578: 
                                return ((ICharacterGrain)grain).Complete().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1168913303: 
                                return ((ICharacterGrain)grain).GetInfo().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -486809198: 
                                return ((ICharacterGrain)grain).GetZoneId().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 526290941:  // ICharacterGrain
                    switch (methodId)
                    {
                        case -934468723:
                            return "IsComplete";
                    case 1168592711:
                            return "BindAccount";
                    case -1256896228:
                            return "GetName";
                    case 316304768:
                            return "SetName";
                    case 1162765578:
                            return "Complete";
                    case -1168913303:
                            return "GetInfo";
                    case -486809198:
                            return "GetZoneId";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansServerInterfaces.Actors
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ZoneGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain GetGrain(System.String primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain), -690228846, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain GetGrain(System.String primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain), -690228846, primaryKey, grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ZoneGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Actors.Luaan.Yggmire.OrleansServerInterface" +
            "s.Actors.IZoneGrain")]
        internal class ZoneGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain
        {
            

            public static Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain), (global::Orleans.Runtime.GrainReference gr) => { return new ZoneGrainReference(gr);}, grainRef, -690228846);
            }
            
            protected internal ZoneGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ZoneGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -690228846;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansServerInterfaces.Actors.Luaan.Yggmire.OrleansServerInterface" +
                        "s.Actors.IZoneGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ZoneGrainReference input = ((ZoneGrainReference)(original));
                return ((ZoneGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ZoneGrainReference input = ((ZoneGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ZoneGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1277021679));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ZoneGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain>> Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain.GetNeighbours()
            {

                return base.InvokeMethodAsync<System.Collections.Generic.IEnumerable<Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain>>(832208624, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain.Subscribe(Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(2143414623, new object[] {observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Actors.ZoneObserverFactory.Cast(observer.AsReference()) : observer} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Actors.IZoneGrain.Unsubscribe(Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-1349169422, new object[] {observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Actors.ZoneObserverFactory.Cast(observer.AsReference()) : observer} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Actors.Luaan.Yggmire.OrleansServerInterface" +
        "s.Actors.IZoneGrain", -690228846)]
    internal class ZoneGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -690228846;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -690228846:  // IZoneGrain
                        switch (methodId)
                        {
                            case 832208624: 
                                return ((IZoneGrain)grain).GetNeighbours().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 2143414623: 
                                return ((IZoneGrain)grain).Subscribe((Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1349169422: 
                                return ((IZoneGrain)grain).Unsubscribe((Luaan.Yggmire.OrleansInterfaces.Actors.IZoneObserver)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1277021679:  // IGrainWithStringKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -690228846:  // IZoneGrain
                    switch (methodId)
                    {
                        case 832208624:
                            return "GetNeighbours";
                    case 2143414623:
                            return "Subscribe";
                    case -1349169422:
                            return "Unsubscribe";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1277021679:  // IGrainWithStringKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansServerInterfaces.Chat
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ChatGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain), -1455653208, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain), -1455653208, primaryKey, grainClassNamePrefix));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain), -1455653208, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain), -1455653208, primaryKey, grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ChatGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Chat.Luaan.Yggmire.OrleansServerInterfaces." +
            "Chat.IChatGrain")]
        internal class ChatGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain
        {
            

            public static Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain), (global::Orleans.Runtime.GrainReference gr) => { return new ChatGrainReference(gr);}, grainRef, -1455653208);
            }
            
            protected internal ChatGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ChatGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -1455653208;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansServerInterfaces.Chat.Luaan.Yggmire.OrleansServerInterfaces." +
                        "Chat.IChatGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ChatGrainReference input = ((ChatGrainReference)(original));
                return ((ChatGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ChatGrainReference input = ((ChatGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ChatGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ChatGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain.SendMessage(string name, string message)
            {

                return base.InvokeMethodAsync<object>(-419561747, new object[] {name, message} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain.Subscribe(string name, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-430058874, new object[] {name, observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain.Unsubscribe(string name, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(425627646, new object[] {name, observer is global::Orleans.Grain ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Chat.Luaan.Yggmire.OrleansServerInterfaces." +
        "Chat.IChatGrain", -1455653208)]
    internal class ChatGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -1455653208;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1455653208:  // IChatGrain
                        switch (methodId)
                        {
                            case -419561747: 
                                return ((IChatGrain)grain).SendMessage((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -430058874: 
                                return ((IChatGrain)grain).Subscribe((String)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 425627646: 
                                return ((IChatGrain)grain).Unsubscribe((String)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1455653208:  // IChatGrain
                    switch (methodId)
                    {
                        case -419561747:
                            return "SendMessage";
                    case -430058874:
                            return "Subscribe";
                    case 425627646:
                            return "Unsubscribe";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace Luaan.Yggmire.OrleansServerInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ClientConversationGrainFactory
    {
        

                        public static IClientConversationGrain GetGrain(long primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IClientConversationGrain), -163582615, primaryKey));
                        }

                        public static IClientConversationGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IClientConversationGrain), -163582615, primaryKey, grainClassNamePrefix));
                        }

                        public static IClientConversationGrain GetGrain(Guid primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IClientConversationGrain), -163582615, primaryKey));
                        }

                        public static IClientConversationGrain GetGrain(Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IClientConversationGrain), -163582615, primaryKey, grainClassNamePrefix));
                        }

            public static IClientConversationGrain Cast(IAddressable grainRef)
            {
                
                return ClientConversationGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.IClientConversationGrain")]
        internal class ClientConversationGrainReference : Orleans.GrainReference, IClientConversationGrain, Orleans.IAddressable
        {
            

            public static IClientConversationGrain Cast(IAddressable grainRef)
            {
                
                return (IClientConversationGrain) GrainReference.CastInternal(typeof(IClientConversationGrain), (GrainReference gr) => { return new ClientConversationGrainReference(gr);}, grainRef, -163582615);
            }

                protected override int InterfaceId { get { return -163582615; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "Luaan.Yggmire.OrleansServerInterfaces.IClientConversationGrain"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return ClientConversationGrainMethodInvoker.GetMethodName(interfaceId, methodId); }
            
            protected internal ClientConversationGrainReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ClientConversationGrainReference input = ((ClientConversationGrainReference)(original));
                return ((ClientConversationGrainReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ClientConversationGrainReference input = ((ClientConversationGrainReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ClientConversationGrainReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public System.Threading.Tasks.Task<string> AskForText(string title, string question)
            {

                return base.InvokeMethodAsync<System.String>(51048912, new object[] {title, question}, TimeSpan.Zero );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.IClientConversationGrain", -163582615)]
    internal class ClientConversationGrainMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return -163582615;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -163582615:  // IClientConversationGrain
                        switch (methodId)
                        {
                            case 51048912: 
                                return await ((IClientConversationGrain)grain).AskForText((String)arguments[0], (String)arguments[1]);
                            default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -163582615:  // IClientConversationGrain
                    switch (methodId)
                    {
                        case 51048912:
                            return "AskForText";
                    case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ClientConversationGrainProperties
    {
        

            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                return retValue;
            }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luaan.Yggmire.OrleansServerInterfaces.Monitoring
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Luaan.Yggmire.OrleansServerInterfaces.Monitoring;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class MonitoringGrainFactory
    {
        

                        public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain), -230746215, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain), -230746215, primaryKey, grainClassNamePrefix));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain), -230746215, primaryKey));
                        }

                        public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain), -230746215, primaryKey, grainClassNamePrefix));
                        }

            public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return MonitoringGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Monitoring.Luaan.Yggmire.OrleansServerInter" +
            "faces.Monitoring.IMonitoringGrain")]
        internal class MonitoringGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain
        {
            

            public static Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain), (global::Orleans.Runtime.GrainReference gr) => { return new MonitoringGrainReference(gr);}, grainRef, -230746215);
            }
            
            protected internal MonitoringGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal MonitoringGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -230746215;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Luaan.Yggmire.OrleansServerInterfaces.Monitoring.Luaan.Yggmire.OrleansServerInter" +
                        "faces.Monitoring.IMonitoringGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                MonitoringGrainReference input = ((MonitoringGrainReference)(original));
                return ((MonitoringGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                MonitoringGrainReference input = ((MonitoringGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return MonitoringGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return MonitoringGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain.RegisterSession()
            {

                return base.InvokeMethodAsync<object>(1130536441, new object[] {} );
            }
            
            System.Threading.Tasks.Task Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain.UnregisterSession()
            {

                return base.InvokeMethodAsync<object>(-345122955, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo> Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain.GetStatus()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo>(-1251605435, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Monitoring.Luaan.Yggmire.OrleansServerInter" +
        "faces.Monitoring.IMonitoringGrain", -230746215)]
    internal class MonitoringGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -230746215;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -230746215:  // IMonitoringGrain
                        switch (methodId)
                        {
                            case 1130536441: 
                                return ((IMonitoringGrain)grain).RegisterSession().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -345122955: 
                                return ((IMonitoringGrain)grain).UnregisterSession().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1251605435: 
                                return ((IMonitoringGrain)grain).GetStatus().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -230746215:  // IMonitoringGrain
                    switch (methodId)
                    {
                        case 1130536441:
                            return "RegisterSession";
                    case -345122955:
                            return "UnregisterSession";
                    case -1251605435:
                            return "GetStatus";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansServerInterfaces_Monitoring_ServerStatusInfoSerialization
    {
        
        static Luaan_Yggmire_OrleansServerInterfaces_Monitoring_ServerStatusInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo input = ((Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.PlayerCount, stream, typeof(Nullable<Int32>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Revision, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo result = new Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo();
            result.PlayerCount = ((Nullable<Int32>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Nullable<Int32>), stream)));
            result.Revision = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo), DeepCopier, Serializer, Deserializer);
        }
    }
}
namespace Luaan.Yggmire.OrleansServerInterfacesSerializers
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    using System.Collections;
    using System.Runtime.InteropServices;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization
    {
        
        static Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(original));
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Characters = ((List<CharacterInformation>)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Characters)));
            result.Name = input.Name;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Characters, stream, typeof(List<CharacterInformation>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            result.Characters = ((List<CharacterInformation>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<CharacterInformation>), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.1053.48452")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansInterfaces_Account_CharacterInformationSerialization
    {
        
        static Luaan_Yggmire_OrleansInterfaces_Account_CharacterInformationSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation();
            result.Id = ((Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Guid), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansInterfaces.Account.CharacterInformation), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
