//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Luaan.Yggmire.OrleansServerInterfaces.Account
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using System.Collections;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class AccountGrainFactory
    {
        

                        public static IAccountGrain GetGrain(long primaryKey, string keyExt)
                        {
                            return Cast(GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(IAccountGrain), 1033839444, primaryKey, keyExt));
                        }

                        public static IAccountGrain GetGrain(long primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(IAccountGrain), 1033839444, primaryKey, keyExt, grainClassNamePrefix));
                        }

                        public static IAccountGrain GetGrain(Guid primaryKey, string keyExt)
                        {
                            return Cast(GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(IAccountGrain), 1033839444, primaryKey, keyExt));
                        }

                        public static IAccountGrain GetGrain(Guid primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(IAccountGrain), 1033839444, primaryKey, keyExt,grainClassNamePrefix));
                        }

            public static IAccountGrain Cast(IAddressable grainRef)
            {
                
                return AccountGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain")]
        internal class AccountGrainReference : Orleans.GrainReference, IAccountGrain, Orleans.IAddressable
        {
            

            public static IAccountGrain Cast(IAddressable grainRef)
            {
                
                return (IAccountGrain) GrainReference.CastInternal(typeof(IAccountGrain), (GrainReference gr) => { return new AccountGrainReference(gr);}, grainRef, 1033839444);
            }

                protected override int InterfaceId { get { return 1033839444; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return AccountGrainMethodInvoker.GetMethodName(interfaceId, methodId); }

            public async System.Threading.Tasks.Task<AccountGrainProperties> GetProperties() 
            { 
                return await base.InvokeMethodAsync<AccountGrainProperties>( -606142484, new object[]{}, TimeSpan.Zero);
            }
            
            
            protected internal AccountGrainReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            public System.Threading.Tasks.Task<string> Name
            {
                get
                {

                return base.InvokeMethodAsync<System.String>(1096274493, new object[] {}, TimeSpan.Zero , options: InvokeMethodOptions.ReadOnly);
                }
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                AccountGrainReference input = ((AccountGrainReference)(original));
                return ((AccountGrainReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                AccountGrainReference input = ((AccountGrainReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return AccountGrainReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public System.Threading.Tasks.Task CaptureSession(Luaan.Yggmire.OrleansInterfaces.ISessionGrain session)
            {

                return base.InvokeMethodAsync<object>(1590561359, new object[] {session is GrainBase ? Luaan.Yggmire.OrleansInterfaces.SessionGrainFactory.Cast(session.AsReference()) : session}, TimeSpan.Zero );
            }
            
            public System.Threading.Tasks.Task<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation> GetState()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation>(-454132849, new object[] {}, TimeSpan.Zero );
            }
            
            public System.Threading.Tasks.Task Create(string password)
            {

                return base.InvokeMethodAsync<object>(-1446207851, new object[] {password}, TimeSpan.Zero );
            }
            
            public System.Threading.Tasks.Task<bool> ValidatePassword(string password)
            {

                return base.InvokeMethodAsync<System.Boolean>(1379941908, new object[] {password}, TimeSpan.Zero );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.IAccountGrain", 1033839444)]
    internal class AccountGrainMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return 1033839444;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1033839444:  // IAccountGrain
                        switch (methodId)
                        {
                            case 1096274493: 
                                return await ((IAccountGrain)grain).Name;
                            case 1590561359: 
                                await ((IAccountGrain)grain).CaptureSession((Luaan.Yggmire.OrleansInterfaces.ISessionGrain)arguments[0]);
                              return true;
                            case -454132849: 
                                return await ((IAccountGrain)grain).GetState();
                            case -1446207851: 
                                await ((IAccountGrain)grain).Create((String)arguments[0]);
                              return true;
                            case 1379941908: 
                                return await ((IAccountGrain)grain).ValidatePassword((String)arguments[0]);
                            case -606142484: return ((IAccountGrain)grain).GetProperties();
                                                        default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1033839444:  // IAccountGrain
                    switch (methodId)
                    {
                        case 1096274493:
                            return "get_Name";
                    case 1590561359:
                            return "CaptureSession";
                    case -454132849:
                            return "GetState";
                    case -1446207851:
                            return "Create";
                    case 1379941908:
                            return "ValidatePassword";
                    case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [System.SerializableAttribute()]
    public static class AccountGrainExtensionMethods
    {
        
static public System.Threading.Tasks.Task<AccountGrainProperties> GetProperties(this IAccountGrain interfaceData) 
            { 
                AccountGrainFactory.AccountGrainReference gref = interfaceData as AccountGrainFactory.AccountGrainReference;
                 return gref.GetProperties();
            }
            
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class AccountGrainProperties
    {
        

            public String Name { get; set; }
            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                retValue["Name"] = Name;
                return retValue;
            }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PlayerGrainFactory
    {
        

                        public static IPlayerGrain GetGrain(long primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IPlayerGrain), 1768646660, primaryKey));
                        }

                        public static IPlayerGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IPlayerGrain), 1768646660, primaryKey, grainClassNamePrefix));
                        }

                        public static IPlayerGrain GetGrain(Guid primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IPlayerGrain), 1768646660, primaryKey));
                        }

                        public static IPlayerGrain GetGrain(Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IPlayerGrain), 1768646660, primaryKey, grainClassNamePrefix));
                        }

            public static IPlayerGrain Cast(IAddressable grainRef)
            {
                
                return PlayerGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.IPlayerGrain")]
        internal class PlayerGrainReference : Orleans.GrainReference, IPlayerGrain, Orleans.IAddressable
        {
            

            public static IPlayerGrain Cast(IAddressable grainRef)
            {
                
                return (IPlayerGrain) GrainReference.CastInternal(typeof(IPlayerGrain), (GrainReference gr) => { return new PlayerGrainReference(gr);}, grainRef, 1768646660);
            }

                protected override int InterfaceId { get { return 1768646660; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "Luaan.Yggmire.OrleansServerInterfaces.Account.IPlayerGrain"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return PlayerGrainMethodInvoker.GetMethodName(interfaceId, methodId); }
            
            protected internal PlayerGrainReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                PlayerGrainReference input = ((PlayerGrainReference)(original));
                return ((PlayerGrainReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                PlayerGrainReference input = ((PlayerGrainReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return PlayerGrainReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Account.IPlayerGrain", 1768646660)]
    internal class PlayerGrainMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return 1768646660;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1768646660:  // IPlayerGrain
                        switch (methodId)
                        {
                            default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1768646660:  // IPlayerGrain
                    switch (methodId)
                    {
                        case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PlayerGrainProperties
    {
        

            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                return retValue;
            }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luaan.Yggmire.OrleansServerInterfaces.Chat
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ChatGrainFactory
    {
        

                        public static IChatGrain GetGrain(long primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IChatGrain), -1455653208, primaryKey));
                        }

                        public static IChatGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IChatGrain), -1455653208, primaryKey, grainClassNamePrefix));
                        }

                        public static IChatGrain GetGrain(Guid primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IChatGrain), -1455653208, primaryKey));
                        }

                        public static IChatGrain GetGrain(Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IChatGrain), -1455653208, primaryKey, grainClassNamePrefix));
                        }

            public static IChatGrain Cast(IAddressable grainRef)
            {
                
                return ChatGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain")]
        internal class ChatGrainReference : Orleans.GrainReference, IChatGrain, Orleans.IAddressable
        {
            

            public static IChatGrain Cast(IAddressable grainRef)
            {
                
                return (IChatGrain) GrainReference.CastInternal(typeof(IChatGrain), (GrainReference gr) => { return new ChatGrainReference(gr);}, grainRef, -1455653208);
            }

                protected override int InterfaceId { get { return -1455653208; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return ChatGrainMethodInvoker.GetMethodName(interfaceId, methodId); }
            
            protected internal ChatGrainReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ChatGrainReference input = ((ChatGrainReference)(original));
                return ((ChatGrainReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ChatGrainReference input = ((ChatGrainReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ChatGrainReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public System.Threading.Tasks.Task SendMessage(string name, string message)
            {

                return base.InvokeMethodAsync<object>(-419561747, new object[] {name, message}, TimeSpan.Zero );
            }
            
            public System.Threading.Tasks.Task Subscribe(string name, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-430058874, new object[] {name, observer is GrainBase ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer}, TimeSpan.Zero );
            }
            
            public System.Threading.Tasks.Task Unsubscribe(string name, Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver observer)
            {
GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(425627646, new object[] {name, observer is GrainBase ? Luaan.Yggmire.OrleansInterfaces.Chat.ChatObserverFactory.Cast(observer.AsReference()) : observer}, TimeSpan.Zero );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Chat.IChatGrain", -1455653208)]
    internal class ChatGrainMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return -1455653208;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1455653208:  // IChatGrain
                        switch (methodId)
                        {
                            case -419561747: 
                                await ((IChatGrain)grain).SendMessage((String)arguments[0], (String)arguments[1]);
                              return true;
                            case -430058874: 
                                await ((IChatGrain)grain).Subscribe((String)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]);
                              return true;
                            case 425627646: 
                                await ((IChatGrain)grain).Unsubscribe((String)arguments[0], (Luaan.Yggmire.OrleansInterfaces.Chat.IChatObserver)arguments[1]);
                              return true;
                            default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1455653208:  // IChatGrain
                    switch (methodId)
                    {
                        case -419561747:
                            return "SendMessage";
                    case -430058874:
                            return "Subscribe";
                    case 425627646:
                            return "Unsubscribe";
                    case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ChatGrainProperties
    {
        

            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                return retValue;
            }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luaan.Yggmire.OrleansServerInterfaces.Monitoring
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using System.Reflection;
    using Orleans.Serialization;
    using Luaan.Yggmire.OrleansServerInterfaces.Monitoring;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class MonitoringGrainFactory
    {
        

                        public static IMonitoringGrain GetGrain(long primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IMonitoringGrain), -230746215, primaryKey));
                        }

                        public static IMonitoringGrain GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IMonitoringGrain), -230746215, primaryKey, grainClassNamePrefix));
                        }

                        public static IMonitoringGrain GetGrain(Guid primaryKey)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IMonitoringGrain), -230746215, primaryKey));
                        }

                        public static IMonitoringGrain GetGrain(Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(GrainFactoryBase.MakeGrainReferenceInternal(typeof(IMonitoringGrain), -230746215, primaryKey, grainClassNamePrefix));
                        }

            public static IMonitoringGrain Cast(IAddressable grainRef)
            {
                
                return MonitoringGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [Orleans.GrainReferenceAttribute("Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain")]
        internal class MonitoringGrainReference : Orleans.GrainReference, IMonitoringGrain, Orleans.IAddressable
        {
            

            public static IMonitoringGrain Cast(IAddressable grainRef)
            {
                
                return (IMonitoringGrain) GrainReference.CastInternal(typeof(IMonitoringGrain), (GrainReference gr) => { return new MonitoringGrainReference(gr);}, grainRef, -230746215);
            }

                protected override int InterfaceId { get { return -230746215; } }

                public override bool IsCompatible(int interfaceId) { return interfaceId == this.InterfaceId; }

                protected override string InterfaceName { get { return "Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain"; } }

                protected override string GetMethodName(int interfaceId, int methodId) { return MonitoringGrainMethodInvoker.GetMethodName(interfaceId, methodId); }
            
            protected internal MonitoringGrainReference(GrainReference reference) : 
                    base(reference)
            {
            }
            
            [Orleans.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                MonitoringGrainReference input = ((MonitoringGrainReference)(original));
                return ((MonitoringGrainReference)(GrainReference.CopyGrainReference(input)));
            }
            
            [Orleans.SerializerMethodAttribute()]
            public static void _Serializer(object original, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                MonitoringGrainReference input = ((MonitoringGrainReference)(original));
                GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [Orleans.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return MonitoringGrainReference.Cast(((Orleans.GrainReference)(GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public System.Threading.Tasks.Task<Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo> GetStatus()
            {

                return base.InvokeMethodAsync<Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo>(-1251605435, new object[] {}, TimeSpan.Zero );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [Orleans.MethodInvokerAttribute("Luaan.Yggmire.OrleansServerInterfaces.Monitoring.IMonitoringGrain", -230746215)]
    internal class MonitoringGrainMethodInvoker : IGrainMethodInvoker
    {
        
        public int InterfaceId
        {
            get
            {
                return -230746215;
            }
        }
        
        public async System.Threading.Tasks.Task<Object> Invoke(IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {
                if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -230746215:  // IMonitoringGrain
                        switch (methodId)
                        {
                            case -1251605435: 
                                return await ((IMonitoringGrain)grain).GetStatus();
                            default: 
                                throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -230746215:  // IMonitoringGrain
                    switch (methodId)
                    {
                        case -1251605435:
                            return "GetStatus";
                    case -606142484:
                            return "GetProperties";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [Serializable()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.814.60418")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class MonitoringGrainProperties
    {
        

            public Dictionary<string,object> AsDictionary()
            {  
                var retValue = new Dictionary<string,object>();
                return retValue;
            }
    }
    
    [Orleans.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansServerInterfaces_Monitoring_ServerStatusInfoSerialization
    {
        
        static Luaan_Yggmire_OrleansServerInterfaces_Monitoring_ServerStatusInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo input = ((Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.PlayerCount, stream, typeof(Nullable<Int32>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Revision, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo result = new Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo();
            result.PlayerCount = ((Nullable<Int32>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Nullable<Int32>), stream)));
            result.Revision = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansServerInterfaces.Monitoring.ServerStatusInfo), DeepCopier, Serializer, Deserializer);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luaan.Yggmire.OrleansServerInterfacesSerializers
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Luaan.Yggmire.OrleansInterfaces.Account;
    using System.Collections;
    using System.Runtime.InteropServices;
    
    
    [Orleans.RegisterSerializerAttribute()]
    internal class Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization
    {
        
        static Luaan_Yggmire_OrleansInterfaces_Account_AccountInformationSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(original));
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Name = input.Name;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation input = ((Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation result = new Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation();
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            Orleans.Serialization.SerializationManager.Register(typeof(Luaan.Yggmire.OrleansInterfaces.Account.AccountInformation), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
