//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyInformationalVersion("0.1.0.bfdd005")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyTitle("Yggmire Server Grains")]
[assembly: AssemblyProduct("Yggmire Engine")]
[assembly: AssemblyCopyright("Copyright © Luaan 2014")]
[assembly: AssemblyCompany("Jiří Borkovec (Luaan)")]
[assembly: ComVisible(false)]


