//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyInformationalVersion("0.1.0.cf1707b")]
[assembly: System.Reflection.AssemblyVersion("0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0")]
[assembly: System.Reflection.AssemblyTitle("Yggmire Server Grains")]
[assembly: System.Reflection.AssemblyProduct("Yggmire Engine")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Luaan 2014")]
[assembly: System.Reflection.AssemblyCompany("Jiří Borkovec (Luaan)")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]


